// ¿Qué es try catch?
const num1 = 20;
const num2 = 30;

try {
    console.log(num1);
    console.log(num2);
    console.log(num3);
} catch (error) {
    console.log(error);
}
